SYAL-879 Shure SystemOn 1.1.3
AVISPL/dal-infrastructure-management-shure-systemon pull request #18
Opened 2022-04-28 17:54 UTC by MaksimR-AVISPL

2022-04-28 22:06 UTC, ShervinM-AVISPL requested changes
Please make sure the 3rd dependency versions in `pom.xml` are up-to-date with latest version specified in https://avi-spl.atlassian.net/wiki/spaces/SYM/pages/803569665/3rd+Party+Software+-+Symphony

If 3rd party dependencies of this adapter are not under the above-mentioned page, please ask Vlad for approval to use it.

2022-04-29 10:26 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/symphony/dal/communicator/shure/ShureSystemOn.java
> +                    latestErrors.put(e.getClass().getSimpleName(), limitErrorMessageByLength(message, 120));
it is 120 characters - I can make this value configurable. But basically this is for the error message crop : 
![image](https://user-images.githubusercontent.com/59052678/165927925-dc8f8d88-810e-4739-86a2-ce6d9525cefe.png)

2022-04-29 10:30 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/symphony/dal/communicator/shure/ShureSystemOn.java
> +            // Setting a thread pool number to be the largest number between 1-10
The largest fitting number, so if there are 100 devices - number of threads in the pool would be 5, or 8 for 200 or 2000. 
Just to have a number of threads to distribute the number of requests evenly

2022-04-29 10:33 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/symphony/dal/communicator/shure/ShureSystemOn.java
>   * @since 4.7
Yeah, this is a legacy version which has been here since the time this adapter was a part of core. Changing it to 1.0.0

2022-04-29 12:54 UTC, ShervinM-AVISPL approved these changes

2022-05-10 12:41 UTC, merged